In [2]:
import numpy as np
import matplotlib.pyplot as plt

## Konvention: alles in Winkelsekunden rechnen

### Observed Zenith angle

In [3]:
time_top = 15 * (np.array([11*60*60 + 42*60 +47, 11*60*60 + 44*60 +8, 11*60*60 + 56*60 +50,
                     11*60*60 + 57*60 +37, 12*60*60 + 4*60 +53, 
                     12*60*60 + 6*60 +3]) - 2*3600) # in arcsec, UT
z_b_top = np.array([39*3600+9*60+32, 39*3600 + 3*60+16, 38*3600 + 6*60+6, 38*3600 + 3*60+7, 37*3600 + 35*60+57, 37*3600 + 32*60+2])

time_bottom = 15 * (np.array([11*60*60 + 49*60 +8, 11*60*60 + 51*60 +3, 11*60*60 + 59*60 +29,
                     12*60*60 + 1*60 +11]) - 2*3600 )# in arcsec, UT
z_b_bottom = np.array([39*3600+12*60+26, 39*3600+4*60+52, 38*3600+29*60+1, 38*3600+21*60+33])


array([34967, 35048, 35810, 35857, 36293, 36363])

### Almanac

In [5]:
GMST_0UT = (14*3600 + 52*60 + 28.7584) * 15
alpha_5 = 2.8197997 * 3600 * 15
alpha_6 = 2.8841898 * 3600 * 15
delta_5 = 16.262748 * 3600
delta_6 = 16.545533 * 3600
phi_1 = 15*60 + 51.58
phi_2 =8.72 * 3600

l = 13 * 3600 + 17*60 + 42.5 # Längengrad in ''

### Interpolation alpha
alpha(t) = m*t + n

In [7]:
m = (alpha_6 - alpha_5)/(3600 * 24) # in arcsec
n = alpha_5
alpha_top = m * time_top + n
alpha_bottom = m * time_bottom + n

### Interpolation delta

In [11]:
m = (delta_6 - delta_5)/(3600 * 24) # in arcsec
n = delta_5
delta_top = m * time_top + n
delta_bottom = m * time_bottom + n

### Hour Angle in arcsec

In [8]:
tau_top = GMST_0UT + time_top * (366.24/365.24) - l - alpha_top
tau_bottom = GMST_0UT + time_bottom * (366.24/365.24) - l - alpha_bottom

In [13]:
# Y ist in Grad!
Y_top = np.arctan(np.cos(tau_top*np.pi/648000) / np.tan(delta_top * np.pi/648000)) # degree
Y_bottom = np.arctan(np.cos(tau_bottom*np.pi/648000) / np.tan(delta_bottom * np.pi/648000)) # degree

# einheitenlos
X_top = np.sin(delta_top*np.pi/648000)*np.sqrt(1 + (np.cos(tau_top*np.pi/648000)/ np.tan(delta_top*np.pi/648000))** 2)
X_bottom = np.sin(delta_bottom*np.pi/648000)*np.sqrt(1 + (np.cos(tau_bottom*np.pi/648000)/ np.tan(delta_bottom*np.pi/648000))** 2)

Y_top

array([-1.28455792, -1.28455886, -1.28456575, -1.28456606, -1.28456835,
       -1.28456861])

In [18]:
b = 52 + 27 / 60 + 24 / 3600 # degree
print(Y_bottom + b > 45)
print(Y_top + b > 45)

[ True  True  True  True]
[ True  True  True  True  True  True]


-> First solution for b!

In [20]:
b_top = 90 - np.arcsin(np.cos(z_b_top*np.pi/648000)/X_top) - Y_top 
b_bottom = 90 - np.arcsin(np.cos(z_b_bottom*np.pi/648000)/X_bottom) - Y_bottom

print(b_bottom)

[90.39648855 90.3943135  90.38399545 90.38184516]
